mex -g '-IH:\eigen-3.3.7' ...
    '-IH:\SuiteSparseBuild\install\include' ...
'-LH:\SuiteSparseBuild\lib\Release' ...
'-LH:\suitesparse-metis-for-windows-master\lapack_windows\x64' ...
     SIMengine/Classes/stdafx.cpp SIMengine/Classes/mersenne.cpp ...
     SIMengine/Classes/SIMcore.cpp SIMengine/Classes/SIMparameters.cpp ...
     SIMengine/Classes/ChemotaxisMapSuiteS.cpp SIMengine/Classes/NecrosisMapSuiteS.cpp...
     SIMengine/Classes/Environment.cpp SIMengine/Classes/TumorCells.cpp ...
     SIMengine/Classes/Lymphocytes.cpp  SIMengine/Classes/GlucoseMap.cpp ...
     SIMengine_interface_mex.cpp SIMengine/Classes/ProtonMap.cpp ...
 -lamd -lcamd -lccolamd -lcholmod -lcolamd -lmetis -lsuitesparseconfig -lcxsparse -lblas -llapack

clear SIMengine_interface_mex.mexw64;
 copyfile('stdafx.mexw64','SIMengine_interface_mex.mexw64')